# /apps/web-client/dockerfile


# ETAPA 1: Construcción
FROM node:18-alpine AS build-step
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ETAPA 2: Servidor Nginx liviano
FROM nginx:alpine
# Vite genera los archivos en /dist
COPY --from=build-step /dist /usr/share/nginx/html

# SOLUCIÓN AL ERROR 404: Configuramos Nginx para que siempre mande al index.html
# Esto permite que rutas como /revision funcionen perfecto
RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]